-- =============================
--     CZYSZCZENIE BAZY
-- =============================

-- Widoki
BEGIN EXECUTE IMMEDIATE 'DROP VIEW VW_RANKING_OGOLNY'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP VIEW VW_RANKING_PRZEDMIOTOW'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP VIEW VW_RANKING_GRUP'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP VIEW VW_OCENY_SZCZEGOLY'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP VIEW VW_SREDNIE_OCEN'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP VIEW VW_ZALICZENIA'; EXCEPTION WHEN OTHERS THEN NULL; END;
/

-- Procedury
BEGIN EXECUTE IMMEDIATE 'DROP PROCEDURE DODAJ_OCENE'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP PROCEDURE SPRAWDZ_ZALICZENIA'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP PROCEDURE POKAZ_OCENY_STUDENTA'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP PROCEDURE POKAZ_RANKING'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP PROCEDURE POKAZ_RANKING_PRZEDMIOTU'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP PROCEDURE ZALOGUJ_ZMIANE'; EXCEPTION WHEN OTHERS THEN NULL; END;
/

-- Funkcje
BEGIN EXECUTE IMMEDIATE 'DROP FUNCTION HASHUJ_HASLO'; EXCEPTION WHEN OTHERS THEN NULL; END;
/

-- Triggery (użytkownicy)
BEGIN EXECUTE IMMEDIATE 'DROP TRIGGER TRG_UTWORZ_UZYTKOWNIKA_STUDENT'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TRIGGER TRG_UTWORZ_UZYTKOWNIKA_NAUCZYCIEL'; EXCEPTION WHEN OTHERS THEN NULL; END;
/

-- Triggery logujące
BEGIN EXECUTE IMMEDIATE 'DROP TRIGGER trg_log_ocena'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TRIGGER trg_log_student'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TRIGGER trg_log_nauczyciel'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TRIGGER trg_log_zapisy'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TRIGGER trg_log_przedmiot'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TRIGGER trg_log_grupa'; EXCEPTION WHEN OTHERS THEN NULL; END;
/

-- Inne triggery (opcjonalne, ale nie używane w aktualnym podejściu)
BEGIN EXECUTE IMMEDIATE 'DROP TRIGGER trg_ocena_historia'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TRIGGER trg_ocena_zaliczenie'; EXCEPTION WHEN OTHERS THEN NULL; END;
/

-- Indeksy (ręcznie tworzone)
BEGIN EXECUTE IMMEDIATE 'DROP INDEX idx_ocena_student'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP INDEX idx_ocena_nauczyciel'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP INDEX idx_ocena_wartosc'; EXCEPTION WHEN OTHERS THEN NULL; END;
/

-- Tabele
BEGIN EXECUTE IMMEDIATE 'DROP TABLE HISTORIA_OCEN CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE LOG_ZMIAN CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE ZALICZENIE CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE OCENA CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE ZAPISY CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE GRUPA CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE PRZEDMIOT CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE NAUCZYCIEL CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE STUDENT CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE UZYTKOWNIK CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE RANKING CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN NULL; END;
/

-- Sekwencje
BEGIN EXECUTE IMMEDIATE 'DROP SEQUENCE ZALICZENIE_SEQ'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP SEQUENCE HISTORIA_OCEN_SEQ'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP SEQUENCE LOG_ZMIAN_SEQ'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
