-- =========================
--      60.916.310 rekordów
-- =========================

DROP TABLE OCENA_K;
CREATE TABLE OCENA_K AS
SELECT
    ROWNUM AS ID,
    O.STUDENT_ID,
    O.PRZEDMIOT_ID,
    O.NAUCZYCIEL_ID,
    O.WARTOSC,
    O.TYP,
    O.DATA_WYSTAWIENIA
FROM OCENA O
CROSS JOIN (
  SELECT LEVEL AS N FROM DUAL CONNECT BY LEVEL <= 95630 -- ~60916310 rekordów
);

SELECT COUNT(*) FROM OCENA_K;

CREATE INDEX IDX_OCENA_K_STUDENT ON OCENA_K(STUDENT_ID);

--drop INDEX idx_ocena_k_student;

EXPLAIN PLAN FOR
SELECT * FROM OCENA_K WHERE STUDENT_ID = 1;

SELECT * FROM TABLE(DBMS_XPLAN.DISPLAY);

-- =========================
--       99.531.250 rekordów
-- =========================

DROP TABLE OCENA_K_2;
CREATE TABLE OCENA_K_2 AS
SELECT
    ROWNUM AS ID,
    O.STUDENT_ID,
    O.PRZEDMIOT_ID,
    O.NAUCZYCIEL_ID,
    O.WARTOSC,
    O.TYP,
    O.DATA_WYSTAWIENIA
FROM OCENA O
CROSS JOIN (
  SELECT LEVEL AS N FROM DUAL CONNECT BY LEVEL <= 156250 -- ~99531250 rekordów
);

SELECT COUNT(*) FROM OCENA_K_2;

CREATE INDEX IDX_OCENA_K_2_STUDENT ON OCENA_K_2(STUDENT_ID);

--drop INDEX idx_ocena_k_2_student;

EXPLAIN PLAN FOR
SELECT * FROM OCENA_K_2 WHERE STUDENT_ID = 1;

SELECT * FROM TABLE(DBMS_XPLAN.DISPLAY);

-- =========================
--       169.601.250 rekordów
-- =========================

DROP TABLE OCENA_K_3;
CREATE TABLE OCENA_K_3 AS
SELECT
    ROWNUM AS ID,
    O.STUDENT_ID,
    O.PRZEDMIOT_ID,
    O.NAUCZYCIEL_ID,
    O.WARTOSC,
    O.TYP,
    O.DATA_WYSTAWIENIA
FROM OCENA O
CROSS JOIN (
  SELECT LEVEL AS N FROM DUAL CONNECT BY LEVEL <= 266250 -- ~169601250 rekordów
);

SELECT COUNT(*) FROM OCENA_K_3;

CREATE INDEX IDX_OCENA_K_3_STUDENT ON OCENA_K_3(STUDENT_ID);

EXPLAIN PLAN FOR
SELECT * FROM OCENA_K_3 WHERE STUDENT_ID = 1;

SELECT * FROM TABLE(DBMS_XPLAN.DISPLAY);